---
title: "Welcome to the Swirl Course Network"
---

---

## For Students:

This website is a directory for free and open source swirl courses. If you're
completely new to R you should read [this](http://swirlstats.com/students.html)
page first which will help you install R, RStudio, and swirl. If you're set up
with R and you're looking for more swirl courses you can browse available 
courses by the name of the course or by the name of the author of the course. 
Click "Browse Courses" above to start browsing! If you're looking for a course 
to start with we recommend the [R Programming](rprog.html) course.

---

## For swirl Course Authors:

Team swirl's ambition is for all publicly available swirl courses to be listed
on this site. Adding your course to the Swirl Course Network offers several
advantages:

- Students can discover your course more easily.
- Your course can be installed with the `install_course()` function.
- Team swirl can more easily provide support for your course.

Click [here](http://swirlstats.com/swirlify/sharing.html#sharing_your_course_on_the_swirl_course_network) to learn how to share your course on the Swirl Course Network.
