---
title: "Swirl Courses Organized by Title"
output:
  html_document:
    toc_depth: 2
    toc_float:
      collapsed: true
---

## A

- [Advanced R Programming](arp.html) by Roger Peng

## C

- [ConoceR](conocer.html) by David Duncan

## D

- [Data Science and R](dsandr.html) by Wush Wu
- [Daten einlesen und kennenlernen](Daten_einlesen_und_kennenlernen.html) by RLab-Team
- [Daten visualisieren mit ggplot2](Daten_visualisieren_mit_ggplot2.html) by RLab-Team
- [Deskriptive Statistik Gelaendeklimatologie](Deskriptive_Statistik_Gelaendeklimatologie.html) by RLab-Team
- [Deskriptive Statistik mit bodenkundlichen Daten](Deskriptive_Statistik_mit_bodenkundlichen_Daten.html) by RLab-Team
- [Deskriptive Statistik und Vergleiche meteorologischer Zeitreihen](Deskriptive_Statistik_und_Vergleiche_meteorologischer_Zeitreihen.html) by RLab-Team

## E

- [Einfuehrung in Datenaufbereitung mit tidyR](Einfuehrung_in_Datenaufbereitung_mit_tidyR.html) by RLab-Team
- [Einfuehrung in Datenhandling und Visualisieren von Klimadaten](Einfuehrung_in_Datenhandling_und_Visualisieren_von_Klimadaten.html) by RLab-Team
- [Exploratory Data Analysis](eda.html) by Team swirl

## G

- [Getting and Cleaning Data](getclean.html) by Team swirl
- [Google Forms Course](gfc.html) by Sean Kross

## M

- [MARSYS Data analysis with R](MARSYS_Data_analysis_with_R.html) by RLab-Team
- [MARSYS Statistik und Programmierung mit R](MARSYS_Statistik_und_Programmierung_mit_R.html) by RLab-Team

## P

- [Programacion Estadistica R](estadistica.html) by Ismael Fernández
- [Programando en R](programando.html) by José R Sosa

## Q

- [qss-swirl](qss.html) by Kosuke Imai

## R

- [R-Grundlagen](R-Grundlagen.html) by RLab-Team
- [R Programming](rprog.html) by Team swirl
- [R Programmieren](R_Programmieren.html) by Stephan Weibelzahl
- [The R Programming Environment](rpe.html) by Roger Peng
- [Regular Expressions](regular_expressions.html) by Jon Calder
- [Regression Models](regmod.html) by Team swirl

## S

- [Statistical Inference](statinf.html) by Team swirl

## V

- [A (Very) Short Introduction to R](A_(very)_short_introduction_to_R.html) by Claudia Brauer